//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Reserv_ID { get; set; }
        public int Reserv_Number { get; set; }
        public System.DateTime Reserv_Date { get; set; }
        public System.TimeSpan Reserv_Time { get; set; }
        public int User_ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
