//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryItem
    {
        public int CategoryItem_ID { get; set; }
        public int Category_ID { get; set; }
        public int Item_ID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Item Item { get; set; }
    }
}
